### ISSUE TITLE
Error: Cannot read property 'toLowerCase' of null

### ISSUE THREAD

**Issue by iamEAP** [run-crank/typescript-cog-utilities#4]
### Repro Steps
1. Install `v0.4.0` of the Salesforce cog (`crank cog:install automatoninc/salesforce:0.4.0 --force --ignore-auth`)
2. Run the **Check a field on a Salesforce Opportunity** step (`crank cog:step automatoninc/salesforce --step=OpportunityFieldEquals` with...
  - **ID Field** set to `Id`
  - **ID Field Value** set to `0064P00000kskUOQAY`
  - **Check Field** set to `Description`
  - **Operator** set to `not contain`
  - **Expected Value** set to `Anything`

### Expected
Because there is no data in the description field, I would expect the step to pass (since "Anything" would not be contained in an empty value).

### Actual
The step results in an error: `There was an error during validation of opportunity field: Cannot read property 'toLowerCase' of null`

![Screen Shot 2019-12-31 at 1 52 15 PM](https://user-images.githubusercontent.com/3496491/71634954-0c24fb00-2bd5-11ea-8eca-b99279633f74.png)

**Comment by iamEAP** [comment]
I think it's reasonable for a Cog to pass `null` or `undefined` to the `util.compare()` method.  We should convert these values to empty strings when doing equality/contains operations.

**Comment by roanlibelo** [comment]
Verified fixed on the ff cogs:
- SalesForce
- Marketo
- Dynamics
- Pardot

Can't verify on this two cogs since this is blocked by https://github.com/run-crank/cog-salesloft/issues/26
- HubSpot
- SalesLoft
